[project]
mapping = "src:.build"

[plugins.minify]
suffixes = [".css"]

[plugins.minify.methods]
css = "native"

[plugins.sass]
mapping = "sass:css"

[plugins.typescript]
mapping = "ts:js"

[flags]
open = true
reload = true
